# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1449814795);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1449814928);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1449846956);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1449814675);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1449846829);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 2);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.link.open_newwindow", 2);
user_pref("browser.migration.version", 27);
user_pref("browser.newtabpage.enhanced", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.privatebrowsing.autostart", true);
user_pref("browser.safebrowsing.enabled", false);
user_pref("browser.safebrowsing.malware.enabled", false);
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.region", "US");
user_pref("browser.slowStartup.averageTime", 20788);
user_pref("browser.slowStartup.samples", 3);
user_pref("dom.allow_scripts_to_close_windows", true);
user_pref("dom.max_chrome_script_run_time", 600);
user_pref("dom.max_script_run_time", 600);
user_pref("extensions.adbeaver.addonId", "e8e2300d-27a0-413d-88b2-526c6ca2b189");
user_pref("extensions.adbeaver.campaign", "publicfox");
user_pref("extensions.adbeaver.foxypid", 1087);
user_pref("extensions.blocklist.pingCountTotal", 4);
user_pref("extensions.blocklist.pingCountVersion", 4);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.dlwatch.aboutconfiglock", true);
user_pref("extensions.dlwatch.addbookmarklock", true);
user_pref("extensions.dlwatch.addonslock", true);
user_pref("extensions.dlwatch.authlastreturn", false);
user_pref("extensions.dlwatch.authopen", false);
user_pref("extensions.dlwatch.blocklinks", false);
user_pref("extensions.dlwatch.bookmarkSidebarLock", true);
user_pref("extensions.dlwatch.customizeToolbarLock", true);
user_pref("extensions.dlwatch.ext", "exe,bat");
user_pref("extensions.dlwatch.hideBookmarksMenu", true);
user_pref("extensions.dlwatch.hideHistoryMenu", true);
user_pref("extensions.dlwatch.hideSafeMode", true);
user_pref("extensions.dlwatch.historylock", true);
user_pref("extensions.dlwatch.libraryLock", true);
user_pref("extensions.dlwatch.lock", true);
user_pref("extensions.dlwatch.optionslock", true);
user_pref("extensions.dlwatch.pass", "225245d6e0a6d5e89ae1869538ebd5b1");
user_pref("extensions.dlwatch.sanitizeLock", true);
user_pref("extensions.dlwatch.urlblockenabled", true);
user_pref("extensions.dlwatch.urlblocklisttype", "blacklistRadio");
user_pref("extensions.dlwatch.urlblocklocations", "");
user_pref("extensions.dlwatch.urlblocktempallow", "");
user_pref("extensions.enabledAddons", "%7B9AA46F4F-4DC7-4c06-97AF-6665170634FE%7D:1.11.6.1-signed,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:38.4.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1449814796);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "38.4.0");
user_pref("extensions.lastPlatformVersion", "38.4.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.publicfox.lastcheck", "1450326843165");
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.experiment.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.xpiState", "{\"app-profile\":{\"{9AA46F4F-4DC7-4c06-97AF-6665170634FE}\":{\"d\":\"/home/pi/.mozilla/firefox/4ivheeod.default/extensions/{9AA46F4F-4DC7-4c06-97AF-6665170634FE}.xpi\",\"e\":true,\"v\":\"1.11.6.1-signed\",\"st\":1449642007000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/iceweasel/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"38.4.0\",\"st\":1449641267000,\"mt\":1446692330000}}}");
user_pref("gecko.buildID", "20151103235259");
user_pref("gecko.mstone", "38.4.0");
user_pref("idle.lastDailyNotification", 1449843314);
user_pref("media.gmp-manager.buildID", "20151103235259");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.database.lastMaintenance", 1449670514);
user_pref("places.history.expiration.transient_current_max_pages", 11393);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("signon.rememberSignons", false);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1449670514);
user_pref("toolkit.startup.last_success", 1450326788);
user_pref("toolkit.telemetry.previousBuildID", "20151103235259");
