# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1423339977);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1423339250);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1423339130);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1423339857);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1423339371);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 92160);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.link.open_newwindow", 2);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.privatebrowsing.autostart", true);
user_pref("browser.safebrowsing.enabled", false);
user_pref("browser.safebrowsing.malware.enabled", false);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150201031458");
user_pref("browser.slowStartup.averageTime", 20732);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.syncPromoViewsLeftMap", "{\"addons\":4}");
user_pref("dom.allow_scripts_to_close_windows", true);
user_pref("dom.max_chrome_script_run_time", 600);
user_pref("dom.max_script_run_time", 600);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B4D498D0A-05AD-4fdb-97B5-8A0AABC1FC5B%7D:0.9.0,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:31.4.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/iceweasel/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1422770810000,\"rdfTime\":1422770810000}}},{\"name\":\"app-profile\",\"addons\":{\"{4D498D0A-05AD-4fdb-97B5-8A0AABC1FC5B}\":{\"descriptor\":\"/home/pi/.mozilla/firefox/xlmmp6o2.default/extensions/{4D498D0A-05AD-4fdb-97B5-8A0AABC1FC5B}.xpi\",\"mtime\":1423339446000}}}]");
user_pref("extensions.lastAppVersion", "31.4.0");
user_pref("extensions.lastPlatformVersion", "31.4.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.experiment.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("gecko.buildID", "20150201031458");
user_pref("gecko.mstone", "31.4.0");
user_pref("idle.lastDailyNotification", 1423339338);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1423339339);
user_pref("places.history.expiration.transient_current_max_pages", 3226);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.rememberSignons", false);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1423339339);
user_pref("toolkit.startup.last_success", 1423340336);
user_pref("toolkit.telemetry.previousBuildID", "20150201031458");
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
